DROP TABLE Contract;
DROP TABLE Attendance;
DROP TABLE Communication;
DROP TABLE Selection;
DROP TABLE Assistance_Request;
DROP TABLE Activity;
DROP TABLE Ovi_User;
DROP TABLE Pap_Pati;
DROP TABLE Instructor;
DROP TABLE Technician;
DROP TABLE Person;
\i person.sql;
\i instructor.sql;
\i activity.sql;
\i pap_pati.sql;
\i ovi_user.sql;
\i attendance.sql;
\i assistance_request.sql;
\i selection.sql;
\i communication.sql;
\i contract.sql;
\i technician.sql;
