\i person_inserts.sql
\i instructor_inserts.sql
\i activity_inserts.sql
\i pap_pati_inserts.sql
\i oviUser_inserts.sql
\i attendance_inserts.sql
\i assistance_request_inserts.sql
\i communication_inserts.sql
\i selection_inserts.sql
\i contract_inserts.sql
\i technician_inserts.sql
