CREATE TABLE Candidacy(

idCandidacy	VARCHAR(10),
status		VARCHAR(40) NOT NULL,
dateAdded	DATE NOT NULL,
idPapPati	VARCHAR(10) NOT NULL,
idPapPatiList	VARCHAR(10) NOT NULL,

CONSTRAINT  cp_candidacy PRIMARY KEY (idCandidacy),
CONSTRAINT  ca_PapPati	 FOREIGN KEY (idPapPati) 
	REFERENCES PapPati(dni)
	ON DELETE  RESTRICT 
	ON UPDATE  CASCADE,
CONSTRAINT  ca_PapPatiList FOREIGN KEY (idPapPatiList)
	REFERENCES PapPatiList(idPap)
	ON DELETE  CASCADE
	ON UPDATE  CASCADE
);
